#FROM nginx:alpine
FROM alpine
RUN apk add --no-cache --update bash python3
#COPY healthcheck.sh /healthcheck.sh
#COPY healthcheck.py /healthcheck.py

#HEALTHCHECK --interval=20s --timeout=10s CMD /healthcheck.sh || exit 1
